figure; supertitle('acute 2:1 stimulus MI')
subplot(231)
plot(circshift((stimMI_b2_avg-stimMI_u2_avg)./stimMI_u2_avg,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI, full dist.')
subplot(232)
plot(circshift((stimMIspike_b2_avg-stimMIspike_u2_avg)./stimMIspike_u2_avg,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/spike, full dist.')
subplot(233)
plot(circshift((stimMIEff_b2_avg-stimMIEff_u2_avg)./stimMIEff_u2_avg,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/H, full dist.')
subplot(234)
plot(circshift((stimMI_b2_avg_pred-stimMI_u2_avg_pred)./stimMI_u2_avg_pred,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI, matched dist.')
subplot(235)
plot(circshift((stimMIspike_b2_avg_pred-stimMIspike_u2_avg_pred)./stimMIspike_u2_avg_pred,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/spike, matched dist.')
subplot(236)
plot(circshift((stimMIEff_b2_avg_pred-stimMIEff_u2_avg_pred)./stimMIEff_u2_avg_pred,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/H, matched dist.')

figure; supertitle('acute 4:1 stimulus MI')
subplot(231)
plot(circshift((stimMI_b4_avg-stimMI_u4_avg)./stimMI_u4_avg,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI, full dist.')
subplot(232)
plot(circshift((stimMIspike_b4_avg-stimMIspike_u4_avg)./stimMIspike_u4_avg,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/spike, full dist.')
subplot(233)
plot(circshift((stimMIEff_b4_avg-stimMIEff_u4_avg)./stimMIEff_u4_avg,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/H, full dist.')
subplot(234)
plot(circshift((stimMI_b4_avg_pred-stimMI_u4_avg_pred)./stimMI_u4_avg_pred,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI, matched dist.')
subplot(235)
plot(circshift((stimMIspike_b4_avg_pred-stimMIspike_u4_avg_pred)./stimMIspike_u4_avg_pred,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/spike, matched dist.')
subplot(236)
plot(circshift((stimMIEff_b4_avg_pred-stimMIEff_u4_avg_pred)./stimMIEff_u4_avg_pred,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/H, matched dist.')

figure; supertitle('acute LC stimulus MI')
subplot(231)
plot(circshift((stimMI_blc_avg-stimMI_u2_avg)./stimMI_u2_avg,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI, full dist.')
subplot(232)
plot(circshift((stimMIspike_blc_avg-stimMIspike_ulc_avg)./stimMIspike_ulc_avg,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/spike, full dist.')
subplot(233)
plot(circshift((stimMIEff_blc_avg-stimMIEff_ulc_avg)./stimMIEff_ulc_avg,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/H, full dist.')
subplot(234)
plot(circshift((stimMI_blc_avg_pred-stimMI_ulc_avg_pred)./stimMI_ulc_avg_pred,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI, matched dist.')
subplot(235)
plot(circshift((stimMIspike_blc_avg_pred-stimMIspike_ulc_avg_pred)./stimMIspike_ulc_avg_pred,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/spike, matched dist.')
subplot(236)
plot(circshift((stimMIEff_blc_avg_pred-stimMIEff_ulc_avg_pred)./stimMIEff_ulc_avg_pred,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/H, matched dist.')

figure; supertitle('acute AT4 stimulus MI')
subplot(231)
plot(circshift((stimMI_bat_avg-stimMI_uat_avg)./stimMI_uat_avg,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI, full dist.')
subplot(232)
plot(circshift((stimMIspike_bat_avg-stimMIspike_uat_avg)./stimMIspike_uat_avg,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/spike, full dist.')
subplot(233)
plot(circshift((stimMIEff_bat_avg-stimMIEff_uat_avg)./stimMIEff_uat_avg,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/H, full dist.')
subplot(234)
plot(circshift((stimMI_bat_avg_pred-stimMI_uat_avg_pred)./stimMI_uat_avg_pred,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI, matched dist.')
subplot(235)
plot(circshift((stimMIspike_bat_avg_pred-stimMIspike_uat_avg_pred)./stimMIspike_uat_avg_pred,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/spike, matched dist.')
subplot(236)
plot(circshift((stimMIEff_bat_avg_pred-stimMIEff_uat_avg_pred)./stimMIEff_uat_avg_pred,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/H, matched dist.')

figure; supertitle('acute AT6 stimulus MI')
subplot(231)
plot(circshift((stimMI_bat6_avg-stimMI_uat6_avg)./stimMI_uat6_avg,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI, full dist.')
subplot(232)
plot(circshift((stimMIspike_bat6_avg-stimMIspike_uat6_avg)./stimMIspike_uat6_avg,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/spike, full dist.')
subplot(233)
plot(circshift((stimMIEff_bat6_avg-stimMIEff_uat6_avg)./stimMIEff_uat6_avg,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/H, full dist.')
subplot(234)
plot(circshift((stimMI_bat6_avg_pred-stimMI_uat6_avg_pred)./stimMI_uat6_avg_pred,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI, matched dist.')
subplot(235)
plot(circshift((stimMIspike_bat6_avg_pred-stimMIspike_uat6_avg_pred)./stimMIspike_uat6_avg_pred,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/spike, matched dist.')
subplot(236)
plot(circshift((stimMIEff_bat6_avg_pred-stimMIEff_uat6_avg_pred)./stimMIEff_uat6_avg_pred,4))
axis square; box off
xlabel('stimulus')
ylabel('% change')
title('MI/H, matched dist.')

% figure; supertitle('acute AT fineori stimulus MI')
% subplot(231)
% plot(circshift((stimMI_bat_fine_avg-stimMI_uat_fine_avg)./stimMI_uat_fine_avg,4))
% axis square; box off
% xlabel('stimulus')
% ylabel('% change')
% title('MI, full dist.')
% subplot(232)
% plot(circshift((stimMIspike_bat_fine_avg-stimMIspike_uat_fine_avg)./stimMIspike_uat_fine_avg,4))
% axis square; box off
% xlabel('stimulus')
% ylabel('% change')
% title('MI/spike, full dist.')
% subplot(233)
% plot(circshift((stimMIEff_bat_fine_avg-stimMIEff_uat_fine_avg)./stimMIEff_uat_fine_avg,4))
% axis square; box off
% xlabel('stimulus')
% ylabel('% change')
% title('MI/H, full dist.')
% subplot(234)
% plot(circshift((stimMI_bat_fine_avg_pred-stimMI_uat_fine_avg_pred)./stimMI_uat_fine_avg_pred,4))
% axis square; box off
% xlabel('stimulus')
% ylabel('% change')
% title('MI, matched dist.')
% subplot(235)
% plot(circshift((stimMIspike_bat_fine_avg_pred-stimMIspike_uat_fine_avg_pred)./stimMIspike_uat_fine_avg_pred,4))
% axis square; box off
% xlabel('stimulus')
% ylabel('% change')
% title('MI/spike, matched dist.')
% subplot(236)
% plot(circshift((stimMIEff_bat_fine_avg_pred-stimMIEff_uat_fine_avg_pred)./stimMIEff_uat_fine_avg_pred,4))
% axis square; box off
% xlabel('stimulus')
% ylabel('% change')
% title('MI/H, matched dist.')